### ISSUE TITLE
Consider wrapping `load-deps` function call in with-pre-wrap

### ISSUE THREAD

**Issue by martinklepsch** [seancorfield/boot-tools-deps#1]
This probably isn't a very common scenario but maybe still worth considering
```clojure
(deftask my-deps []
  (comp (with-pass-thru _
          (println "first task"))
        (deps)))
```

With the current task `load-deps` will be called at the time the task pipeline is constructed rather than when the task is actually being ran. The following would preserve the task order:

```clojure
  (boot/with-pass-thru _
    (load-deps {:config-paths      config-paths
                :classpath-aliases classpath-aliases
                :resolve-aliases   resolve-aliases
                :repeatable        repeatable
                :verbose           verbose})))
```

**Comment by seancorfield** [comment]
Most of the Boot code I've seen sets up dependencies etc at the start of the task and then has `with-pass-thru` or some `comp`osed pipeline of tasks -- which is why I wrote `deps` the way I did -- but you raise an interesting question.

Perhaps it's worth having two tasks: one that works as `deps` does now, and one that does the `load-deps` inside `with-pass-thru`?

**Comment by martinklepsch** [comment]
I see where you're coming from. I don't really have any strong opinions either way, especially since people can just use `load-deps` if they want a different behavior. Feel free to close I guess :)

**Comment by martinklepsch** [comment]
Also, thanks a lot for making this 😸  💚

**Comment by seancorfield** [comment]
OK, I'll close this out. If the issue comes up again, as a problem in actual usage, I can always add that extra task.
