### ISSUE TITLE
Put tools.deps in a pod?

### ISSUE THREAD

**Issue by martinklepsch** [seancorfield/boot-tools-deps#5]
Not sure if this is worth it or even possible but could we put the tools.deps machinery into a pod?

Leaving this here for later consideration.

**Comment by seancorfield** [comment]
I think a pod is overkill for the general case -- a Boot pipeline that wants to get dependencies via `tools.deps` instead of hardcoded into `build.boot`, which includes the command-line only case (no `build.boot`) -- but for a `build.boot` file already leveraging pods, it makes sense to be able to run this all inside a pod.

I think a pre-req for that is splitting `load-deps` in two: a function that calls into `tools.deps` and merges all the `deps.edn` stuff and returns the paths and dependencies as data, and then `load-deps` could just merge that data into the (global) environment.

Then move the loading of `tools.deps` into a function and making the use of `tools.deps` dynamic (I tried this originally and it defeated me -- I do not want to be forced into a pod in all cases -- so it just needs more time spent on solving it).

Finally those can be recombined for the case of building a pod based on `deps.edn` files.

**Comment by seancorfield** [comment]
Fixed in 0.2.0!
