### ISSUE TITLE
:scope doesn't affect transitive deps

### ISSUE THREAD

**Issue by oakes** [seancorfield/boot-tools-deps#7]
I noticed that if I make a dependency `:scope "test"`, all of its transitive deps are still included in any jar file that I build. After looking at the code, I believe this is because you are using tools.deps to resolve the dependencies before passing them to Boot. Any reason why you don't just let Boot do the resolving?

**Comment by oakes** [comment]
BTW the following change fixed the issue for me. I'm not sure if this breaks anything else. Perhaps a better solution would be to make tools.deps resolve non-maven deps, but let Boot resolve maven ones?

https://github.com/oakes/boot-tools-deps/commit/7e696ce6098e00bcd10d87b33a90b0af98f63ad5

**Comment by seancorfield** [comment]
I haven't tried your change directly but, looking at it, I'm pretty sure it will break resolve aliases functionality (since `resolve-args` is no longer used).

When I talked to @puredanger about `:scope` I got the impression that it "worked by accident" rather than being explicitly supported within `tools.deps` so this might be a case where it doesn't do the right thing (namely, propagating the `:scope` across transitive dependencies)?

**Comment by puredanger** [comment]
Hey Sean, I don't recall talking about `:scope` with you in the past (we did talk about `:exclusions`). The `:scope` is retrieved from dependencies for informational purposes, but only `:compile` scope dependencies are kept when walking the dependency graph. 

Note that `:scope` is not "propagated"  in Maven. Rather, when using the API you specify an execution context. That context implies via the [rules](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) which scoped transitive dependencies are kept when walking the graph. However, tools.deps doesn't use that code, follow those rules, or allow you to specify an execution context.

**Comment by oakes** [comment]
I'm going to try getting rid of :scope and using aliases like Alex mentioned in [my gist](https://gist.github.com/oakes/778de5ca7fd1a764829bcab14a1c42a9). As I mentioned there, though, I am worried about tasks that build both ClojureScript and jars. The cljs task will need access to the `:extra-deps`, but I'll need to figure out how to keep the jar task from including them in the artifact. I suppose with :scope that distinction happens automatically.

**Comment by seancorfield** [comment]
Thank you @puredanger -- yes, you are right, we were discussing `:exclusions`. My bad! But thank you also for the clarification on scope/context. Am I correct in assuming that those are out of scope for tools.deps and not likely to be supported at any point?

I'll have a think about the implications of this. It feels like the right thing to do is split the resolve code so that the Boot task will handle aliases and merging etc, but will just hand the result off to Boot to deal with, rather than relying on tools.deps resolving (to produce the full list of dependencies). This fits with https://dev.clojure.org/jira/browse/TDEPS-18

Part of the reason I went down that path in the first place was to (try to) ensure that you'd get the exact same set of dependencies in Boot as you got from `clj` -- but that is a lossy process, as far as scope is concerned, and Boot already handles that as expected.

**Comment by oakes** [comment]
Here's my second attempt: https://github.com/oakes/boot-tools-deps/commit/c13274438e4a244a23c2c8978c8dc2ff7e4a0036 It makes sure to merge the `:extra-deps` from `resolve-args`, so aliases still work. I may be missing other stuff though.

I changed all my projects to use an alias for ClojureScript deps, and that *mostly* eliminated the need for `:scope "test"`, but there are a few cases where I still need it. Take for example the [deploy task](https://github.com/oakes/Nightlight/blob/430c70ebeda1fc132286bc0daa619d1e006f9b1c/build.boot#L30) for Nightlight. I deploy Nightlight's UI as a prebuilt JS file, so I run the `cljs` task and then `pom` `jar` and `push`. I don't want those ClojureScript deps in the final Nightlight artifact; I only want them to be available for the `cljs` task. The second fix I just linked to seems to work for me -- it allows aliases to work, but also allows Boot to do the resolving.

**Comment by seancorfield** [comment]
But it won't handle default-deps or override-deps from aliases.

**Comment by seancorfield** [comment]
I think at this point, I'm going to refactor the code so I can more easily write a test suite and then any PRs will at least have tests to check against!

**Comment by oakes** [comment]
Yeah I figured I missed some things :-) I guess we basically want to do everything that `resolve-deps` does except the the final step where it grabs transitive deps?

**Comment by seancorfield** [comment]
And those functions -- in `tools.deps` -- are all private so I want to spend some time thinking carefully about how to proceed, before making any changes.

**Comment by oakes** [comment]
@seancorfield Please feel free to close this issue -- I no longer consider it a problem, since the notion of `:scope` is really maven specific and so trying to completely support it here is probably a mismatch. I ended up finding a really simple solution to my problem: I read from my deps.edn directly and put the deps I want into the `:dependencies` option of the `pom` task. See for example [here](https://github.com/oakes/Nightlight/blob/b77536202f64b4c076c317afdcff33e78ffbb1b6/build.boot#L23). That allowed me to take my projects off of my fork too. Yay!

**Comment by seancorfield** [comment]
OK, thanks for the update.
